# -*- coding: utf-8 -*-
"""statistical_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQTGVxBs8VuGYxUkUj3JxAXq_xio0KuZ
"""

import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("business_data.csv")
df.head()

df.info()

df.describe()

print("Mean Values")
print(df[['Quantity','Price','Total_Sales']].mean())

print("\nMedian Values")
print(df[['Quantity','Price','Total_Sales']].median())

print("\nStandard Deviation")
print(df[['Quantity','Price','Total_Sales']].std())

mean_sales = df['Total_Sales'].mean()
sem = stats.sem(df['Total_Sales'])

ci = stats.t.interval(
    0.95,
    len(df['Total_Sales']) - 1,
    loc=mean_sales,
    scale=sem
)

print("Average Sales:", mean_sales)
print("95% Confidence Interval:", ci)

correlation = df[['Quantity','Price','Total_Sales']].corr()
correlation

sns.heatmap(correlation, annot=True)
plt.title("Correlation Matrix")
plt.show()

t_stat, p_value = stats.ttest_1samp(df['Total_Sales'], 0)

print("T-statistic:", t_stat)
print("P-value:", p_value)

east = df[df['Region']=="East"]['Total_Sales']
west = df[df['Region']=="West"]['Total_Sales']

t_stat, p_value = stats.ttest_ind(east, west)

print("T-statistic:", t_stat)
print("P-value:", p_value)

corr, p_value = stats.pearsonr(df['Price'], df['Total_Sales'])

print("Correlation:", corr)
print("P-value:", p_value)

X = df[['Price','Quantity']]
y = df['Total_Sales']

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

print(model.summary())

sns.regplot(x=df['Price'], y=df['Total_Sales'])
plt.title("Price vs Sales Regression")
plt.show()
